version: '3'
services:
  praxis-backend:
    build: backend/.
    environment:
      MONGO_URL: 'mongodb://praxis-db:27017/userdb'
    depends_on:
      - praxis-db
    ports:
      - '3000:3000'
  praxis-db:
    image: mongo
    expose:
      - '27017'
